name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: agrima-06
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%23c084fc&color_dots=%23151b2e,%235b21b6,%237c3aed,%23a855f7,%23d946ef
            dist/github-contribution-grid-snake-dark.svg?color_snake=%23e879f9&color_dots=%23151b2e,%236d28d9,%238b5cf6,%23c026d3,%23f472b6

      - name: Push Snake to Output Branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          target_branch: output
          commit_message: "Update contribution snake"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
